[package]
name = "hex_color"
version = "3.0.1" # update html_root_url in src/lib.rs and README.md

authors = ["Sean C. Roach <me@seancroach.dev>"]
categories = ["data-structures", "graphics", "multimedia::images", "no-std"]
description = "A simple, lightweight library for working with RGB(A) hexadecimal colors."
edition = "2021"
keywords = ["color", "hex", "rgb", "rgba"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/seancroach/hex_color"

[features]
default = ["std"]

rand = ["dep:rand"]
serde = ["dep:serde", "dep:arrayvec"]
std = ["rand?/std", "rand?/std_rng"]

[dependencies]
arrayvec = { version = "0.7", optional = true, default-features = false }
rand = { version = "0.8", optional = true, default-features = false }
serde = { version = "1.0", optional = true, default-features = false }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]
